[project]
name = "mip-mcp"
version = "0.1.0"
description = "MIP optimization server using Model Context Protocol with PuLP"
readme = "README.md"
authors = [
    { name = "ohtaman", email = "ohtamans@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.6",
    "pyscipopt>=5.5.0",
    "pulp>=2.7.0",
    "pydantic>=2.0.0",
    "pyyaml>=6.0",
    "mip>=1.15.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
]
cloud = [
    "google-cloud-secret-manager>=2.16.0",
]

[project.scripts]
mip-mcp = "mip_mcp:cli"
mip-mcp-server = "mip_mcp.mcp_server:mcp_main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
