name: Main Branch CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run tests
      run: make test

    - name: Run linting
      run: make lint

    - name: Check code formatting
      run: |
        uv run ruff format --check src/ tests/

    - name: Build package
      run: |
        uv build

    - name: Test package installation
      run: |
        uv pip install dist/*.whl
        uv run python -c "from src.mip_mcp.server import MIPMCPServer; print('Package import successful')"

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/